DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS account;

CREATE TABLE user (
    if INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE account (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    owner_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    balance FLOAT NOT NULL, 
    FOREIGN KEY (owner_id) REFERENCES user (id)
)